import pytest
from app.spec.orm_codegen import generate_prisma_schema, generate_typeorm_entities, generate_sqlalchemy_models
from app.ddl.export import snapshot_json_to_sql

def test_codegen_stable_output_composite_keys():
    snapshot = {
        "relations": [
            {"relation_oid": 1, "relation_name": "t1", "schema_name": "public", "relation_kind": "r"},
            {"relation_oid": 2, "relation_name": "t2", "schema_name": "public", "relation_kind": "r"}
        ],
        "columns": [
            {"relation_oid": 1, "column_name": "c1", "data_type": "integer", "is_not_null": True, "column_position": 1},
            {"relation_oid": 1, "column_name": "c2", "data_type": "text", "is_not_null": True, "column_position": 2},
            {"relation_oid": 2, "column_name": "c3", "data_type": "integer", "is_not_null": True, "column_position": 1},
            {"relation_oid": 2, "column_name": "c1", "data_type": "integer", "is_not_null": True, "column_position": 2}
        ],
        "pk_columns": [
            {"relation_oid": 1, "column_name": "c1"},
            {"relation_oid": 1, "column_name": "c2"}
        ],
        "fk_edges": [
            {"child_relation_oid": 2, "child_column_name": "c1", "parent_relation_oid": 1, "parent_column_name": "c1"}
        ]
    }

    prisma = generate_prisma_schema(snapshot)
    assert prisma == """// Generated by pg-erd-cloud — Prisma schema (edit freely)
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model T1 {
  c1 Int
  c2 String
  t2s T2[]
  @@id([c1, c2])
  @@map("t1")
}

model T2 {
  c3 Int
  c1 Int
  c1 T1 @relation(fields: [c1], references: [c1])
  @@map("t2")
}
"""

    typeorm = generate_typeorm_entities(snapshot)
    assert typeorm == """// Generated by pg-erd-cloud — TypeORM entities (edit freely)
import {
  Column,
  Entity,
  JoinColumn,
  ManyToOne,
  OneToMany,
  PrimaryColumn,
} from 'typeorm';

@Entity("t1")
export class T1 {
  @PrimaryColumn()
  c1!: number;

  @PrimaryColumn()
  c2!: string;

  @OneToMany(() => T2, (child) => child)
  t2s?: T2[];
}

@Entity("t2")
export class T2 {
  @Column()
  c3!: number;

  @Column()
  c1!: number;

  @ManyToOne(() => T1)
  @JoinColumn({ name: "c1" })
  c1?: T1;
}
"""

    sqlalchemy = generate_sqlalchemy_models(snapshot)
    assert sqlalchemy == """# Generated by pg-erd-cloud — SQLAlchemy 2.0 models (edit freely)
from __future__ import annotations

import datetime as dt
import uuid
from decimal import Decimal

from sqlalchemy import ForeignKey
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class T1(Base):
    __tablename__ = 't1'
    c1: Mapped[int] = mapped_column(primary_key=True)
    c2: Mapped[str] = mapped_column(primary_key=True)


class T2(Base):
    __tablename__ = 't2'
    c3: Mapped[int] = mapped_column()
    c1: Mapped[int] = mapped_column(ForeignKey('t1.c1'))
"""

def test_codegen_hostile_missing_metadata():
    snapshot = {
        "relations": [
            {"relation_oid": 1, "relation_name": "t1", "schema_name": "public", "relation_kind": "r"},
        ],
        "columns": [
            {"relation_oid": 1, "column_name": "c1", "data_type": "integer"}
        ]
    }

    prisma = generate_prisma_schema(snapshot)
    assert prisma == """// Generated by pg-erd-cloud — Prisma schema (edit freely)
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model T1 {
  c1 Int?
  @@map("t1")
}
"""

    typeorm = generate_typeorm_entities(snapshot)
    assert typeorm == """// Generated by pg-erd-cloud — TypeORM entities (edit freely)
import {
  Column,
  Entity,
  JoinColumn,
  ManyToOne,
  OneToMany,
  PrimaryColumn,
} from 'typeorm';

@Entity("t1")
export class T1 {
  @Column({nullable: true})
  c1?: number | null;
}
"""

    sqlalchemy = generate_sqlalchemy_models(snapshot)
    assert sqlalchemy == """# Generated by pg-erd-cloud — SQLAlchemy 2.0 models (edit freely)
from __future__ import annotations

import datetime as dt
import uuid
from decimal import Decimal

from sqlalchemy import ForeignKey
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class T1(Base):
    __tablename__ = 't1'
    c1: Mapped[int | None] = mapped_column()
"""
