"""Tests for :mod:`app.release.sbom` — CycloneDX SBOM from lockfiles."""

from __future__ import annotations

import json

import pytest

from app.release.sbom import (
    SBOM_SPEC_VERSION,
    build_sbom,
    parse_npm_lock,
    parse_pip_lock,
)

_PIP_LOCK = """\
# generated by a tool
--index-url https://pypi.org/simple

anyio==4.4.0 \\
    --hash=sha256:1111111111111111111111111111111111111111111111111111111111111111 \\
    --hash=sha256:2222222222222222222222222222222222222222222222222222222222222222
click==8.1.7
-e file:///local/thing
"""

_NPM_LOCK = {
    "name": "frontend",
    "lockfileVersion": 3,
    "packages": {
        "": {"name": "frontend", "version": "0.1.0"},
        "node_modules/nanoid": {
            "version": "5.0.7",
            "integrity": "sha512-oooooooooooooooooooooo",
        },
        "node_modules/@xyflow/react": {
            "version": "12.3.0",
            "integrity": "sha512-rrrrrrrrrrrrrrrrrrrrrr",
        },
        "node_modules/leftpad": {"link": True},
        "frontend/node_modules/dedupe-me": {
            "version": "1.0.0",
            "integrity": "sha512-dddddddddddddddddddddd",
        },
    },
}


def test_parse_pip_lock_happy_path_and_hashes() -> None:
    """A name==version line yields one component with its collected hashes."""

    components = parse_pip_lock(_PIP_LOCK)
    by_name = {c["name"]: c for c in components}
    assert set(by_name) == {"anyio", "click"}
    assert by_name["anyio"]["version"] == "4.4.0"
    assert by_name["anyio"]["purl"] == "pkg:pypi/anyio@4.4.0"
    assert by_name["anyio"]["hashes"] == [
        {"alg": "SHA-256", "content": "1" * 64},
        {"alg": "SHA-256", "content": "2" * 64},
    ]


def test_parse_pip_lock_skips_comments_blanks_and_options() -> None:
    """Comment, blank, -e and --index-url lines produce no components."""

    components = parse_pip_lock(_PIP_LOCK)
    assert all(c["name"] not in {"", "-e", "--index-url"} for c in components)
    assert len(components) == 2


def test_parse_pip_lock_component_without_hashes() -> None:
    """A bare pin still parses, with an empty hash list."""

    [component] = parse_pip_lock("click==8.1.7\n")
    assert component["hashes"] == []


def test_parse_npm_lock_happy_path() -> None:
    """Each node_modules entry with a version becomes a component."""

    components = parse_npm_lock(_NPM_LOCK)
    by_name = {c["name"]: c for c in components}
    assert by_name["nanoid"]["version"] == "5.0.7"
    assert by_name["nanoid"]["purl"] == "pkg:npm/nanoid@5.0.7"
    assert by_name["nanoid"]["hashes"] == [
        {"alg": "SHA-512", "content": "oooooooooooooooooooooo"}
    ]


def test_parse_npm_lock_skips_root_and_linkless_versionless() -> None:
    """The root key and a link-only (no version) entry are skipped."""

    names = {c["name"] for c in parse_npm_lock(_NPM_LOCK)}
    assert "frontend" not in names  # the "" root entry
    assert "leftpad" not in names  # link: true, no version


def test_parse_npm_lock_scoped_and_nested_names() -> None:
    """Scoped packages keep the @scope/ prefix; nested paths take the last segment."""

    names = {c["name"] for c in parse_npm_lock(_NPM_LOCK)}
    assert "@xyflow/react" in names
    assert "dedupe-me" in names  # from frontend/node_modules/dedupe-me


def test_parse_npm_lock_rejects_non_dict() -> None:
    """A non-dict lock is a programming error."""

    with pytest.raises(ValueError, match="npm_lock"):
        parse_npm_lock(["not", "a", "dict"])  # type: ignore[arg-type]


def test_parse_npm_lock_missing_packages_key() -> None:
    """A lock without a packages map yields no components (no crash)."""

    assert parse_npm_lock({"name": "x", "lockfileVersion": 3}) == []


def test_build_sbom_shape_and_spec_version() -> None:
    """The bom has the CycloneDX envelope and the declared spec version."""

    bom = build_sbom(
        pip_lock=_PIP_LOCK,
        npm_lock=_NPM_LOCK,
        component_name="pg-erd-cloud",
        component_version="0.1.0",
        generated_at="2026-09-03T00:00:00Z",
    )
    assert bom["bomFormat"] == "CycloneDX"
    assert bom["specVersion"] == SBOM_SPEC_VERSION == "1.6"
    assert bom["version"] == 1
    assert bom["metadata"]["timestamp"] == "2026-09-03T00:00:00Z"
    assert bom["metadata"]["component"] == {
        "type": "application",
        "name": "pg-erd-cloud",
        "version": "0.1.0",
    }


def test_build_sbom_sorted_and_deduped() -> None:
    """Components are sorted by (type, name, version) and unique per purl."""

    bom = build_sbom(
        pip_lock="click==8.1.7\nclick==8.1.7\n",
        npm_lock={"packages": {"node_modules/nanoid": {"version": "5.0.7"}}},
        component_name="app",
        component_version="1.0.0",
        generated_at="t",
    )
    keys = [(c["type"], c["name"], c["version"]) for c in bom["components"]]
    assert keys == sorted(keys)
    purls = [c["purl"] for c in bom["components"]]
    assert len(purls) == len(set(purls))
    # sorted by name: "click" before "nanoid"
    assert purls == ["pkg:pypi/click@8.1.7", "pkg:npm/nanoid@5.0.7"]


def test_build_sbom_round_trips_through_json() -> None:
    """The whole document is JSON-serializable."""

    bom = build_sbom(
        pip_lock=_PIP_LOCK,
        npm_lock=_NPM_LOCK,
        component_name="app",
        component_version="1.0.0",
        generated_at="t",
    )
    assert json.loads(json.dumps(bom)) == bom


@pytest.mark.parametrize("field", ["component_name", "component_version", "generated_at"])
def test_build_sbom_blank_metadata_rejected(field: str) -> None:
    """Blank envelope metadata raises ValueError naming the field."""

    kwargs = {
        "pip_lock": "",
        "npm_lock": {},
        "component_name": "app",
        "component_version": "1.0.0",
        "generated_at": "t",
    }
    kwargs[field] = "   "
    with pytest.raises(ValueError, match=field):
        build_sbom(**kwargs)  # type: ignore[arg-type]


def test_build_sbom_non_dict_npm_lock_rejected() -> None:
    """build_sbom surfaces the npm_lock type error from parse_npm_lock."""

    with pytest.raises(ValueError, match="npm_lock"):
        build_sbom(
            pip_lock="",
            npm_lock="nope",  # type: ignore[arg-type]
            component_name="app",
            component_version="1.0.0",
            generated_at="t",
        )
