"""Regression tests for reproducible backend dependency-lock commands."""

from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
DEVELOPMENT_LOCK = REPOSITORY_ROOT / "backend" / "requirements-dev.lock"


def test_development_lock_records_repository_root_relative_command() -> None:
    """Keep the generated lock header executable from the repository root."""

    header = DEVELOPMENT_LOCK.read_text(encoding="utf-8").splitlines()[:2]

    assert header == [
        "# This file was autogenerated by uv via the following command:",
        (
            "#    uv pip compile backend/pyproject.toml --python-version 3.10 "
            + "--generate-hashes --extra dev -o backend/requirements-dev.lock"
        ),
    ]
