import type { Node, Edge } from "@xyflow/react";
import type { TableNodeData } from "./convert";
import { sanitizeHandleId } from "./handleUtils";

function sanitizeClassName(name: string): string {
  let sanitized = name.replace(/[^a-zA-Z0-9_]/g, "_");
  if (!/^[a-zA-Z]/.test(sanitized)) {
    sanitized = "Entity_" + sanitized;
  }
  return sanitized.charAt(0).toUpperCase() + sanitized.slice(1);
}

function sanitizeFieldName(name: string): string {
  let sanitized = name.replace(/[^a-zA-Z0-9_]/g, "_");
  if (!/^[a-zA-Z]/.test(sanitized)) {
    sanitized = "field_" + sanitized;
  }
  return sanitized;
}

function mapToTypeORMType(pgType: string): string {
  const t = pgType.toLowerCase();

  if (t.includes("int") || t.includes("serial") || t.includes("float") || t.includes("double") || t.includes("numeric") || t.includes("real") || t.includes("decimal")) {
    return "number";
  }
  if (t.includes("bool")) {
    return "boolean";
  }
  if (t.includes("time") || t.includes("date")) {
    return "Date";
  }
  if (t.includes("json") || t.includes("jsonb")) {
    return "object";
  }
  if (t.includes("bytea") || t.includes("binary") || t.includes("blob")) {
    return "Buffer";
  }
  return "string";
}

export function exportTypeorm(nodes: Node<TableNodeData>[], edges: Edge[]): string {
  if (nodes.length === 0) {
    return "// No tables to export\n";
  }

  let output = `// Generated by pg-erd-cloud — TypeORM entities (edit freely)\nimport {\n  Column,\n  Entity,\n  JoinColumn,\n  ManyToOne,\n  OneToMany,\n  PrimaryColumn,\n} from 'typeorm';\n\n`;

  const nodesById = new Map<string, Node<TableNodeData>>();
  for (const n of nodes) {
    nodesById.set(n.id, n);
  }

  const incomingRelationsByNode = new Map<string, Array<{ sourceModel: string, sourceField: string, targetColName: string }>>();
  const edgesProcessed = new Map<string, { targetModel: string, sourceField: string, targetColName: string }>();

  for (const edge of edges) {
    const sourceNode = nodesById.get(edge.source);
    const targetNode = nodesById.get(edge.target);
    if (!sourceNode || !targetNode) continue;

    let sourceField = "";
    if (edge.sourceHandle?.startsWith("src-")) {
      sourceField = edge.sourceHandle.slice(4);
    } else if (sourceNode.data.columns.length > 0) {
      sourceField = sourceNode.data.columns[0].column_name;
    }

    let targetColName = "id";
    if (edge.targetHandle?.startsWith("tgt-")) {
      targetColName = edge.targetHandle.slice(4);
    }

    if (sourceField) {
      const relList = incomingRelationsByNode.get(edge.target) || [];
      relList.push({
        sourceModel: sanitizeClassName(sourceNode.data.title),
        sourceField: sourceField,
        targetColName
      });
      incomingRelationsByNode.set(edge.target, relList);

      edgesProcessed.set(edge.id, {
        targetModel: sanitizeClassName(targetNode.data.title),
        sourceField: sourceField,
        targetColName
      });
    }
  }

  for (const node of nodes) {
    const tableNameParts = node.data.title.split('.');
    let schemaName = '';
    let tableName = '';
    if (tableNameParts.length > 1) {
      schemaName = tableNameParts[0];
      tableName = tableNameParts.slice(1).join('.');
    } else {
      tableName = node.data.title;
    }

    const modelName = sanitizeClassName(tableName);
    let entityArgs = `"${tableName}"`;
    if (schemaName && schemaName !== "public") {
      entityArgs = `{ name: "${tableName}", schema: "${schemaName}" }`;
    }

    output += `@Entity(${entityArgs})\nexport class ${modelName} {\n`;

    for (const col of node.data.columns) {
      const fieldName = sanitizeFieldName(col.column_name);
      const tsType = mapToTypeORMType(col.data_type);

      let decoratorArgs: string[] = [];
      if (fieldName !== col.column_name) {
        decoratorArgs.push(`name: "${col.column_name}"`);
      }
      if (!col.is_not_null && !col.is_pk) {
        decoratorArgs.push(`nullable: true`);
      }

      const decoratorStr = decoratorArgs.length > 0 ? `{ ${decoratorArgs.join(", ")} }` : "";
      const decorator = col.is_pk ? `@PrimaryColumn(${decoratorStr})` : `@Column(${decoratorStr})`;

      const optional = !col.is_not_null && !col.is_pk ? "?" : "!";
      const unionNull = !col.is_not_null && !col.is_pk ? " | null" : "";

      const comment = (tsType !== "string" || col.data_type.toLowerCase().startsWith("text") || col.data_type.toLowerCase().startsWith("varchar") || col.data_type.toLowerCase().startsWith("char")) ? ` // ${col.data_type}` : "";

      output += `  ${decorator}\n`;
      output += `  ${fieldName}${optional}: ${tsType}${unionNull};${comment}\n\n`;
    }

    for (const [edgeId, edgeInfo] of edgesProcessed.entries()) {
      const edge = edges.find(e => e.id === edgeId);
      if (edge && edge.source === node.id) {
        const relationFieldName = sanitizeFieldName(edgeInfo.sourceField).replace(/_id$/, '') || `related_${edgeInfo.targetModel.toLowerCase()}`;
        output += `  @ManyToOne(() => ${edgeInfo.targetModel})\n`;
        output += `  @JoinColumn({ name: "${edgeInfo.sourceField}" })\n`;
        output += `  ${relationFieldName}?: ${edgeInfo.targetModel};\n\n`;
      }
    }

    const incoming = incomingRelationsByNode.get(node.id) || [];
    for (const inc of incoming) {
      let fieldList = inc.sourceModel.charAt(0).toLowerCase() + inc.sourceModel.slice(1);
      if (!fieldList.endsWith('s')) {
        fieldList += "s";
      }
      output += `  @OneToMany(() => ${inc.sourceModel}, (child) => child)\n`;
      output += `  ${fieldList}?: ${inc.sourceModel}[];\n\n`;
    }

    // Remove the trailing newline
    if (output.endsWith('\n\n')) {
      output = output.slice(0, -1);
    }

    output += `}\n\n`;
  }

  return output;
}
