"""Generate a GraphQL SDL (schema definition language) from a snapshot.

API-first teams bootstrap GraphQL servers from their database; handing them a
typed SDL (with FK-derived object relations) extends forward engineering to
the API layer, alongside the ORM codegen.

Pure and dialect-agnostic. GraphQL names must match ``[_A-Za-z][_0-9A-Za-z]*``,
so identifiers are sanitized; the original name is kept in a comment when it
had to be changed. Unmapped SQL types fall back to ``String``.
"""

from __future__ import annotations

import re
from typing import Any

_GQL_TYPES: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"^(big)?serial|^bigint"), "ID_OR_INT"),  # resolved below
    (re.compile(r"^(small)?int|^integer"), "Int"),
    (re.compile(r"^bool"), "Boolean"),
    (re.compile(r"^(real|float|double|numeric|decimal)"), "Float"),
    (re.compile(r"^(timestamp|datetime|date$|time($|\())"), "String"),
    (re.compile(r"^uuid"), "ID"),
]

_NAME_RE = re.compile(r"[^_0-9A-Za-z]")


def _gql_name(raw: str, *, pascal: bool = False) -> str:
    cleaned = _NAME_RE.sub("_", raw)
    if pascal:
        parts = re.split(r"[_]+", cleaned)
        cleaned = "".join(p.capitalize() for p in parts if p) or "Type"
    # after any casing: GraphQL names must not start with a digit
    if not cleaned or cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned


def _map_type(data_type: str, is_pk: bool) -> str:
    lowered = data_type.strip().lower()
    for pattern, mapped in _GQL_TYPES:
        if pattern.search(lowered):
            if mapped == "ID_OR_INT":
                return "ID" if is_pk else "Int"
            return mapped
    return "ID" if is_pk else "String"


def generate_graphql_sdl(snapshot: dict[str, Any] | None) -> str:
    """Render GraphQL type definitions with FK-derived relations."""
    snapshot = snapshot or {}
    relations = [
        r for r in snapshot.get("relations") or []
        if (r.get("relation_kind") or "r") in ("r", "p")
    ]
    cols_by_oid: dict[Any, list[dict[str, Any]]] = {}
    for c in snapshot.get("columns") or []:
        cols_by_oid.setdefault(c.get("relation_oid"), []).append(c)
    for cols in cols_by_oid.values():
        cols.sort(key=lambda c: c.get("column_position") or 0)
    pk_by_oid: dict[Any, set[str]] = {}
    for pk in snapshot.get("pk_columns") or []:
        pk_by_oid.setdefault(pk.get("relation_oid"), set()).add(str(pk.get("column_name")))
    rel_by_oid = {r.get("relation_oid"): r for r in relations}
    fk_by_child: dict[tuple[Any, str], dict[str, Any]] = {}
    children_of: dict[Any, list[dict[str, Any]]] = {}
    for e in snapshot.get("fk_edges") or []:
        fk_by_child[(e.get("child_relation_oid"), str(e.get("child_column_name")))] = e
        children_of.setdefault(e.get("parent_relation_oid"), []).append(e)

    lines = ["# Generated by pg-erd-cloud — GraphQL SDL (edit freely)"]
    for rel in relations:
        oid = rel.get("relation_oid")
        table = str(rel.get("relation_name"))
        type_name = _gql_name(table, pascal=True)
        header = f"type {type_name} {{"
        if type_name.lower() != table.lower().replace("_", ""):
            pass  # name derived from table; no comment needed for plain snake_case
        lines += ["", header]
        for col in cols_by_oid.get(oid, []):
            name = str(col.get("column_name"))
            field = _gql_name(name)
            is_pk = name in pk_by_oid.get(oid, set())
            gql_type = _map_type(str(col.get("data_type") or ""), is_pk)
            bang = "!" if col.get("is_not_null") else ""
            note = f"  # was: {name}" if field != name else ""
            lines.append(f"  {field}: {gql_type}{bang}{note}")
            fk = fk_by_child.get((oid, name))
            if fk is not None:
                parent = rel_by_oid.get(fk.get("parent_relation_oid"))
                if parent is not None:
                    pname = _gql_name(str(parent.get("relation_name")), pascal=True)
                    rel_field = _gql_name(re.sub(r"_id$", "", name) or pname.lower())
                    lines.append(f"  {rel_field}: {pname}")
        for e in children_of.get(oid, []):
            child = rel_by_oid.get(e.get("child_relation_oid"))
            if child is None:
                continue
            cname = _gql_name(str(child.get("relation_name")), pascal=True)
            list_field = _gql_name(str(child.get("relation_name")))
            lines.append(f"  {list_field}: [{cname}!]")
        lines.append("}")

    if relations:
        lines += ["", "type Query {"]
        for rel in relations:
            type_name = _gql_name(str(rel.get("relation_name")), pascal=True)
            field = _gql_name(str(rel.get("relation_name")))
            lines.append(f"  {field}: [{type_name}!]")
        lines.append("}")
    return "\n".join(lines) + "\n"
