"""Generate ORM model code (SQLAlchemy 2.0 / Prisma) from a snapshot.

Forward engineering all the way to application code: reverse-engineer a legacy
database, then hand developers ready-to-edit ORM models instead of making them
retype every table. Most diagram tools stop at DDL — this is a differentiator
(see docs/erd-tool-feature-research.md).

Pure and dialect-agnostic. Type mapping is best-effort: unmapped SQL types fall
back to ``str``/``String`` with the original type kept in a comment, so the
output always imports/parses.
"""

from __future__ import annotations

import json
import keyword
import re
from typing import Any

_PY_TYPES: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"^(big)?serial|^(small|big)?int|^integer"), "int"),
    (re.compile(r"^bool"), "bool"),
    (re.compile(r"^(timestamp|datetime)"), "dt.datetime"),
    (re.compile(r"^date$"), "dt.date"),
    (re.compile(r"^time($|\()"), "dt.time"),
    (re.compile(r"^(numeric|decimal)"), "Decimal"),
    (re.compile(r"^(real|float|double)"), "float"),
    (re.compile(r"^uuid"), "uuid.UUID"),
    (re.compile(r"^(json|jsonb)"), "dict"),
    (re.compile(r"^bytea|^(var)?binary|^blob"), "bytes"),
    (re.compile(r"^(text|(var)?char|character|enum)"), "str"),
]

_PRISMA_TYPES: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"^bigserial|^bigint"), "BigInt"),
    (re.compile(r"^serial|^(small)?int|^integer"), "Int"),
    (re.compile(r"^bool"), "Boolean"),
    (re.compile(r"^(timestamp|datetime|date$|time($|\())"), "DateTime"),
    (re.compile(r"^(numeric|decimal)"), "Decimal"),
    (re.compile(r"^(real|float|double)"), "Float"),
    (re.compile(r"^(json|jsonb)"), "Json"),
    (re.compile(r"^bytea|^(var)?binary|^blob"), "Bytes"),
]


def _map_type(data_type: str, table: list[tuple[re.Pattern[str], str]], default: str) -> str:
    lowered = data_type.strip().lower()
    for pattern, mapped in table:
        if pattern.search(lowered):
            return mapped
    return default


def _snake_name(value: object, fallback: str) -> str:
    name = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", str(value or ""))
    name = re.sub(r"[^0-9a-zA-Z]+", "_", name).strip("_").lower()
    name = name or fallback
    if name[0].isdigit():
        name = f"{fallback}_{name}"
    if keyword.iskeyword(name):
        name = f"{name}_"
    return name


def _class_name(table_name: str) -> str:
    parts = re.split(r"[^0-9a-zA-Z]+", table_name)
    name = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if not name or name[0].isdigit():
        name = f"Table{name}"
    return f"{name}Model" if keyword.iskeyword(name) else name


def _column_names(cols: list[dict[str, Any]]) -> dict[str, str]:
    return {str(col.get("column_name")): _snake_name(col.get("column_name"), "column") for col in cols}


def _index(snapshot: dict[str, Any] | None) -> dict[str, Any]:
    snapshot = snapshot or {}
    relations = [
        r for r in snapshot.get("relations") or []
        if (r.get("relation_kind") or "r") in ("r", "p")
    ]
    cols_by_oid: dict[Any, list[dict[str, Any]]] = {}
    for c in snapshot.get("columns") or []:
        cols_by_oid.setdefault(c.get("relation_oid"), []).append(c)
    for cols in cols_by_oid.values():
        cols.sort(key=lambda c: c.get("column_position") or 0)
    pk_by_oid: dict[Any, set[str]] = {}
    for pk in snapshot.get("pk_columns") or []:
        pk_by_oid.setdefault(pk.get("relation_oid"), set()).add(str(pk.get("column_name")))
    fk_by_child: dict[tuple[Any, str], dict[str, Any]] = {}
    for e in snapshot.get("fk_edges") or []:
        fk_by_child[(e.get("child_relation_oid"), str(e.get("child_column_name")))] = e
    rel_by_oid = {r.get("relation_oid"): r for r in relations}
    return {
        "relations": relations,
        "cols_by_oid": cols_by_oid,
        "pk_by_oid": pk_by_oid,
        "fk_by_child": fk_by_child,
        "rel_by_oid": rel_by_oid,
    }


def generate_sqlalchemy_models(snapshot: dict[str, Any] | None) -> str:
    """Render SQLAlchemy 2.0 (Mapped/mapped_column) models."""
    ix = _index(snapshot)
    lines = [
        "# Generated by pg-erd-cloud — SQLAlchemy 2.0 models (edit freely)",
        "from __future__ import annotations",
        "",
        "import datetime as dt",
        "import uuid",
        "from decimal import Decimal",
        "",
        "from sqlalchemy import ForeignKey",
        "from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column",
        "",
        "",
        "class Base(DeclarativeBase):",
        "    pass",
    ]
    for rel in ix["relations"]:
        oid = rel.get("relation_oid")
        table = str(rel.get("relation_name"))
        schema = str(rel.get("schema_name"))
        lines += ["", "", f"class {_class_name(table)}(Base):"]
        if rel.get("relation_comment"):
            lines.append(f"    {str(rel['relation_comment'])!r}")
            lines.append("")
        lines.append(f"    __tablename__ = {table!r}")
        if schema and schema != "public":
            lines.append(f"    __table_args__ = {{'schema': {schema!r}}}")
        cols = ix["cols_by_oid"].get(oid, [])
        col_names = _column_names(cols)
        if not cols:
            lines.append("    pass")
            continue
        for col in cols:
            name = str(col.get("column_name"))
            attr = col_names[name]
            raw_type = str(col.get("data_type") or "")
            py_type = _map_type(raw_type, _PY_TYPES, "str")
            not_null = bool(col.get("is_not_null"))
            annotated = py_type if not_null else f"{py_type} | None"
            args = [repr(name)] if attr != name else []
            fk = ix["fk_by_child"].get((oid, name))
            if fk is not None:
                parent = ix["rel_by_oid"].get(fk.get("parent_relation_oid"))
                if parent is not None:
                    target = f'{parent.get("schema_name")}.{parent.get("relation_name")}.{fk.get("parent_column_name")}'
                    if parent.get("schema_name") == "public":
                        target = f'{parent.get("relation_name")}.{fk.get("parent_column_name")}'
                    args.append(f"ForeignKey({target!r})")
            if name in ix["pk_by_oid"].get(oid, set()):
                args.append("primary_key=True")
            comment = "" if _map_type(raw_type, _PY_TYPES, "?") != "?" else f"  # type: {raw_type}"
            call = f"mapped_column({', '.join(args)})" if args else "mapped_column()"
            lines.append(f"    {attr}: Mapped[{annotated}] = {call}{comment}")
    return "\n".join(lines) + "\n"


def generate_prisma_schema(snapshot: dict[str, Any] | None) -> str:
    """Render a Prisma schema (models with @id/@map; relations as field pairs)."""
    ix = _index(snapshot)
    lines = [
        "// Generated by pg-erd-cloud — Prisma schema (edit freely)",
        'datasource db {',
        '  provider = "postgresql"',
        '  url      = env("DATABASE_URL")',
        '}',
    ]
    # child fk list per parent for reverse relation fields
    children_of: dict[Any, list[dict[str, Any]]] = {}
    for (child_oid, _), e in ix["fk_by_child"].items():
        children_of.setdefault(e.get("parent_relation_oid"), []).append(e)

    for rel in ix["relations"]:
        oid = rel.get("relation_oid")
        table = str(rel.get("relation_name"))
        model = _class_name(table)
        lines += ["", f"model {model} {{"]
        cols = ix["cols_by_oid"].get(oid, [])
        col_names = _column_names(cols)
        pk_cols = ix["pk_by_oid"].get(oid, set())
        for col in cols:
            name = str(col.get("column_name"))
            field_name = col_names[name]
            raw_type = str(col.get("data_type") or "")
            p_type = _map_type(raw_type, _PRISMA_TYPES, "String")
            optional = "" if col.get("is_not_null") else "?"
            attrs = []
            if name in pk_cols and len(pk_cols) == 1:
                attrs.append("@id")
            if field_name != name:
                attrs.append(f"@map({json.dumps(name)})")
            comment = "" if _map_type(raw_type, _PRISMA_TYPES, "?") != "?" and p_type != "String" or raw_type.lower().startswith(("text", "varchar", "char")) else f" // {raw_type}"
            lines.append(f"  {field_name} {p_type}{optional}{' ' + ' '.join(attrs) if attrs else ''}{comment}")
        # relation fields
        for (child_oid, child_col), e in ix["fk_by_child"].items():
            if child_oid != oid:
                continue
            parent = ix["rel_by_oid"].get(e.get("parent_relation_oid"))
            if parent is None:
                continue
            pmodel = _class_name(str(parent.get("relation_name")))
            child_field = col_names.get(child_col, _snake_name(child_col, "column"))
            parent_cols = ix["cols_by_oid"].get(e.get("parent_relation_oid"), [])
            parent_field = _column_names(parent_cols).get(str(e.get("parent_column_name")), _snake_name(e.get("parent_column_name"), "column"))
            field = re.sub(r"_id$", "", child_field) or _snake_name(pmodel, "relation")
            lines.append(
                f"  {field} {pmodel} @relation(fields: [{child_field}], references: [{parent_field}])"
            )
        for e in children_of.get(oid, []):
            child = ix["rel_by_oid"].get(e.get("child_relation_oid"))
            if child is None:
                continue
            cmodel = _class_name(str(child.get("relation_name")))
            lines.append(f"  {cmodel[0].lower() + cmodel[1:]}s {cmodel}[]")
        if len(pk_cols) > 1:
            ordered = [col_names[str(c.get("column_name"))] for c in cols if str(c.get("column_name")) in pk_cols]
            lines.append(f"  @@id([{', '.join(ordered)}])")
        lines.append(f"  @@map({json.dumps(table)})")
        lines.append("}")
    return "\n".join(lines) + "\n"


_TS_TYPES: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"^(big)?serial|^(small|big)?int|^integer|^(real|float|double|numeric|decimal)"), "number"),
    (re.compile(r"^bool"), "boolean"),
    (re.compile(r"^(timestamp|datetime|date$|time($|\())"), "Date"),
    (re.compile(r"^(json|jsonb)"), "object"),
    (re.compile(r"^bytea|^(var)?binary|^blob"), "Buffer"),
]


def generate_typeorm_entities(snapshot: dict[str, Any] | None) -> str:
    """Render TypeORM entity classes (TypeScript decorators)."""
    ix = _index(snapshot)
    lines = [
        "// Generated by pg-erd-cloud — TypeORM entities (edit freely)",
        "import {",
        "  Column,",
        "  Entity,",
        "  JoinColumn,",
        "  ManyToOne,",
        "  OneToMany,",
        "  PrimaryColumn,",
        "} from 'typeorm';",
    ]
    # reverse-relation index: parent oid -> child fk edges
    children_of: dict[Any, list[dict[str, Any]]] = {}
    for (child_oid, _), e in ix["fk_by_child"].items():
        children_of.setdefault(e.get("parent_relation_oid"), []).append(e)

    for rel in ix["relations"]:
        oid = rel.get("relation_oid")
        table = str(rel.get("relation_name"))
        schema = str(rel.get("schema_name"))
        cls = _class_name(table)
        entity_args = json.dumps(table) if schema == "public" else f"{{ name: {json.dumps(table)}, schema: {json.dumps(schema)} }}"
        lines += ["", f"@Entity({entity_args})", f"export class {cls} {{"]
        cols = ix["cols_by_oid"].get(oid, [])
        col_names = _column_names(cols)
        for col in cols:
            name = str(col.get("column_name"))
            field_name = col_names[name]
            raw_type = str(col.get("data_type") or "")
            ts_type = _map_type(raw_type, _TS_TYPES, "string")
            nullable = not col.get("is_not_null")
            is_pk = name in ix["pk_by_oid"].get(oid, set())
            options = []
            if field_name != name:
                options.append(f"name: {json.dumps(name)}")
            if nullable and not is_pk:
                options.append("nullable: true")
            decorator = "@PrimaryColumn" if is_pk else "@Column"
            decorator = f"{decorator}({{{', '.join(options)}}})" if options else f"{decorator}()"
            comment = "" if _map_type(raw_type, _TS_TYPES, "?") != "?" and ts_type != "string" or raw_type.lower().startswith(("text", "varchar", "char")) else f" // {raw_type}"
            lines.append(f"  {decorator}")
            lines.append(f"  {field_name}{'?' if nullable else '!'}: {ts_type}{' | null' if nullable else ''};{comment}")
            lines.append("")
        for (child_oid, child_col), e in ix["fk_by_child"].items():
            if child_oid != oid:
                continue
            parent = ix["rel_by_oid"].get(e.get("parent_relation_oid"))
            if parent is None:
                continue
            pcls = _class_name(str(parent.get("relation_name")))
            child_field = col_names.get(child_col, _snake_name(child_col, "column"))
            field = re.sub(r"_id$", "", child_field) or _snake_name(pcls, "relation")
            lines.append(f"  @ManyToOne(() => {pcls})")
            lines.append(f"  @JoinColumn({{ name: {json.dumps(child_col)} }})")
            lines.append(f"  {field}?: {pcls};")
            lines.append("")
        for e in children_of.get(oid, []):
            child = ix["rel_by_oid"].get(e.get("child_relation_oid"))
            if child is None:
                continue
            ccls = _class_name(str(child.get("relation_name")))
            field = ccls[0].lower() + ccls[1:] + "s"
            lines.append(f"  @OneToMany(() => {ccls}, (child) => child)")
            lines.append(f"  {field}?: {ccls}[];")
            lines.append("")
        while lines and lines[-1] == "":
            lines.pop()
        lines.append("}")
    return "\n".join(lines) + "\n"
