"""Render a snapshot as a self-contained public schema-docs HTML page.

The dbdocs-style deliverable: a share-link URL anyone can open and read —
tables, columns, keys, relationships — without an account. Security posture:

* every value from the snapshot is HTML-escaped (database identifiers and
  comments are untrusted input);
* the page is fully self-contained (inline CSS, no scripts, no external
  requests), so a strict CSP can be applied by the caller.
"""

from __future__ import annotations

import html
from typing import Any

_CSS = """
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
margin:2rem auto;max-width:60rem;padding:0 1rem;color:#1a202c;background:#fff}
h1{font-size:1.5rem;border-bottom:2px solid #e2e8f0;padding-bottom:.5rem}
h2{font-size:1.15rem;margin-top:2rem}
table{border-collapse:collapse;width:100%;font-size:.875rem}
th,td{border:1px solid #e2e8f0;padding:.35rem .6rem;text-align:left}
th{background:#f7fafc}
.badge{display:inline-block;font-size:.7rem;font-weight:600;padding:.1rem .4rem;
border-radius:.25rem;margin-left:.3rem}
.pk{background:#fefcbf;color:#744210}.fk{background:#bee3f8;color:#2a4365}
.nn{background:#e2e8f0;color:#2d3748}
.comment{color:#718096}
footer{margin-top:3rem;font-size:.75rem;color:#a0aec0}
""".strip()


def _esc(value: object) -> str:
    return html.escape(str(value)) if value is not None else ""


def render_schema_docs_html(snapshot: dict[str, Any] | None, title: str = "Schema") -> str:
    """Render the snapshot as a static, escaped, self-contained HTML document."""
    snapshot = snapshot or {}
    relations = sorted(
        (r for r in snapshot.get("relations") or []),
        key=lambda r: (str(r.get("schema_name")), str(r.get("relation_name"))),
    )
    cols_by_oid: dict[Any, list[dict[str, Any]]] = {}
    for c in snapshot.get("columns") or []:
        cols_by_oid.setdefault(c.get("relation_oid"), []).append(c)
    for cols in cols_by_oid.values():
        cols.sort(key=lambda c: c.get("column_position") or 0)
    pk_by_oid: dict[Any, set[str]] = {}
    for pk in snapshot.get("pk_columns") or []:
        pk_by_oid.setdefault(pk.get("relation_oid"), set()).add(str(pk.get("column_name")))
    fk_cols: dict[tuple[Any, str], str] = {}
    rel_by_oid = {r.get("relation_oid"): r for r in relations}
    for e in snapshot.get("fk_edges") or []:
        parent = rel_by_oid.get(e.get("parent_relation_oid"))
        if parent is not None:
            fk_cols[(e.get("child_relation_oid"), str(e.get("child_column_name")))] = (
                f"{parent.get('schema_name')}.{parent.get('relation_name')}."
                f"{e.get('parent_column_name')}"
            )

    parts = [
        "<!doctype html>",
        '<html lang="en"><head><meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>{_esc(title)}</title>",
        f"<style>{_CSS}</style></head><body>",
        f"<h1>{_esc(title)}</h1>",
        f"<p class='comment'>{len(relations)} relations · generated by pg-erd-cloud</p>",
    ]
    for rel in relations:
        oid = rel.get("relation_oid")
        qname = f"{rel.get('schema_name')}.{rel.get('relation_name')}"
        kind = " (view)" if str(rel.get("relation_kind") or "r") in ("v", "m") else ""
        parts.append(f"<h2>{_esc(qname)}{_esc(kind)}</h2>")
        if rel.get("relation_comment"):
            parts.append(f"<p class='comment'>{_esc(rel['relation_comment'])}</p>")
        parts.append(
            "<table><tr><th>#</th><th>Column</th><th>Type</th><th>Keys</th>"
            "<th>Comment</th></tr>"
        )
        for i, col in enumerate(cols_by_oid.get(oid, []), start=1):
            name = str(col.get("column_name"))
            badges = []
            if name in pk_by_oid.get(oid, set()):
                badges.append("<span class='badge pk'>PK</span>")
            ref = fk_cols.get((oid, name))
            if ref:
                badges.append(f"<span class='badge fk'>FK → {_esc(ref)}</span>")
            if col.get("is_not_null"):
                badges.append("<span class='badge nn'>NN</span>")
            parts.append(
                f"<tr><td>{i}</td><td>{_esc(name)}</td>"
                f"<td>{_esc(col.get('data_type'))}</td>"
                f"<td>{''.join(badges)}</td>"
                f"<td class='comment'>{_esc(col.get('column_comment') or '')}</td></tr>"
            )
        parts.append("</table>")
    parts.append("<footer>Read-only schema documentation.</footer></body></html>")
    return "\n".join(parts)
