from __future__ import annotations

from collections.abc import Iterable


def _q(ident: str) -> str:
    """Quote a PostgreSQL identifier."""

    # Quote identifier with double-quotes, escaping internal quotes.
    return '"' + ident.replace('"', '""') + '"'


def _qname(schema: str, name: str) -> str:
    """Quote a schema-qualified name."""
    return f"{_q(schema)}.{_q(name)}"


def snapshot_json_to_sql(snapshot: dict) -> str:
    """Generate PostgreSQL DDL from a captured snapshot.

    This is MVP-grade forward engineering (export):
    - Creates schemas and tables (columns only)
    - Adds PK/UNIQUE/CHECK inside CREATE TABLE
    - Adds FKs after all tables (order-safe)
    - Adds indexes using saved pg_get_indexdef output

    Limitations (intentional, MVP): partitioning clauses and some table options are not reconstructed.
    """

    relations = snapshot.get("relations", [])
    columns = snapshot.get("columns", [])
    constraints = snapshot.get("constraints", [])
    indexes = snapshot.get("indexes", [])

    tables = [r for r in relations if r.get("relation_kind") in ("r", "p")]

    cols_by_oid: dict[int, list[dict]] = {}
    for c in columns:
        oid = c.get("relation_oid")
        if isinstance(oid, int):
            cols_by_oid.setdefault(oid, []).append(c)

    constraints_by_oid: dict[int, list[dict]] = {}
    for con in constraints:
        oid = con.get("relation_oid")
        if isinstance(oid, int):
            constraints_by_oid.setdefault(oid, []).append(con)

    schemas: set[str] = {
        t.get("schema_name") for t in tables if isinstance(t.get("schema_name"), str)
    }

    lines: list[str] = []
    lines.append("-- Generated by pg-erd-cloud (MVP)\n")

    for s in sorted(schemas):
        lines.append(f"CREATE SCHEMA IF NOT EXISTS {_q(s)};")
    if schemas:
        lines.append("")

    # CREATE TABLE + inline constraints (PK/UNIQUE/CHECK)
    for t in tables:
        schema = t.get("schema_name")
        name = t.get("relation_name")
        oid = t.get("relation_oid")
        kind = t.get("relation_kind")
        if not (
            isinstance(schema, str) and isinstance(name, str) and isinstance(oid, int)
        ):
            continue

        if kind == "p":
            lines.append(
                f"-- NOTE: {_qname(schema, name)} is partitioned; partition definition not included in MVP export"
            )

        col_defs: list[str] = []
        for c in sorted(
            cols_by_oid.get(oid, []), key=lambda x: int(x.get("column_position") or 0)
        ):
            col_name = c.get("column_name")
            data_type = c.get("data_type")
            if not (isinstance(col_name, str) and isinstance(data_type, str)):
                continue
            parts = [f"{_q(col_name)} {data_type}"]
            if c.get("has_default") and isinstance(c.get("default_expr"), str):
                parts.append(f"DEFAULT {c.get('default_expr')}")
            if c.get("is_not_null") is True:
                parts.append("NOT NULL")
            col_defs.append(" ".join(parts))

        table_cons: list[str] = []
        for con in constraints_by_oid.get(oid, []):
            ctype = con.get("constraint_type")
            if ctype not in ("p", "u", "c"):
                continue
            cname = con.get("constraint_name")
            cdef = con.get("constraint_def")
            if isinstance(cname, str) and isinstance(cdef, str):
                table_cons.append(f"CONSTRAINT {_q(cname)} {cdef}")

        all_defs = col_defs + table_cons
        lines.append(f"CREATE TABLE IF NOT EXISTS {_qname(schema, name)} (")
        for i, d in enumerate(all_defs):
            comma = "," if i < len(all_defs) - 1 else ""
            lines.append(f"  {d}{comma}")
        lines.append(");")
        lines.append("")

    # FKs after tables
    fk_cons = [c for c in constraints if c.get("constraint_type") == "f"]
    if fk_cons:
        lines.append("-- Foreign keys")
    for con in fk_cons:
        schema = con.get("schema_name")
        table = con.get("relation_name")
        cname = con.get("constraint_name")
        cdef = con.get("constraint_def")
        if not (
            isinstance(schema, str)
            and isinstance(table, str)
            and isinstance(cname, str)
            and isinstance(cdef, str)
        ):
            continue
        lines.append(
            f"ALTER TABLE {_qname(schema, table)} ADD CONSTRAINT {_q(cname)} {cdef};"
        )
    if fk_cons:
        lines.append("")

    # Indexes (use saved pg_get_indexdef output)
    if indexes:
        lines.append("-- Indexes")
    for ix in indexes:
        ix_def = ix.get("index_def")
        if not isinstance(ix_def, str):
            continue
        if not ix_def.strip().endswith(";"):
            ix_def = ix_def.strip() + ";"
        lines.append(ix_def)

    lines.append("")
    return "\n".join(lines)
